# Generated by Django 2.2.28 on 2022-12-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
