# Generated by Django 2.2.28 on 2022-12-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20221209_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(max_length=20, verbose_name='name'),
        ),
    ]
