# Generated by Django 2.2.28 on 2022-12-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20221209_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='domain_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='framework',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='app',
            name='type',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='app',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
