# Generated by Django 2.2.28 on 2022-12-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20221209_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='type',
            field=models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.')], max_length=100),
        ),
    ]
