# Generated by Django 2.2.28 on 2022-12-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20221209_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='type',
            field=models.CharField(choices=[('Web', 'Web'), ('Mobile', 'Mobile')], max_length=100),
        ),
    ]
