# Generated by Django 2.2.28 on 2022-12-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20221209_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='framework',
            field=models.CharField(choices=[('Django', 'Django'), ('React', 'React')], max_length=100),
        ),
    ]
