# Generated by Django 2.2.28 on 2022-12-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20221209_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'plan',
            },
        ),
        migrations.AlterField(
            model_name='app',
            name='domain_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
