# Generated by Django 2.2.28 on 2022-12-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20221209_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('1', 'Free'), ('2', 'Standard'), ('3', 'Pro')], max_length=30)),
                ('app', models.IntegerField(max_length=100)),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
    ]
